/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.clients.basicavro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderStatus extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1184851061837560249L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderStatus\",\"namespace\":\"io.confluent.examples.clients.basicavro\",\"fields\":[{\"name\":\"statusMessage\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderStatus> ENCODER =
      new BinaryMessageEncoder<OrderStatus>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderStatus> DECODER =
      new BinaryMessageDecoder<OrderStatus>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderStatus> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderStatus> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderStatus> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderStatus>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderStatus to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderStatus from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderStatus instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderStatus fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String statusMessage;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderStatus() {}

  /**
   * All-args constructor.
   * @param statusMessage The new value for statusMessage
   */
  public OrderStatus(java.lang.String statusMessage) {
    this.statusMessage = statusMessage;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return statusMessage;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: statusMessage = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'statusMessage' field.
   * @return The value of the 'statusMessage' field.
   */
  public java.lang.String getStatusMessage() {
    return statusMessage;
  }


  /**
   * Sets the value of the 'statusMessage' field.
   * @param value the value to set.
   */
  public void setStatusMessage(java.lang.String value) {
    this.statusMessage = value;
  }

  /**
   * Creates a new OrderStatus RecordBuilder.
   * @return A new OrderStatus RecordBuilder
   */
  public static io.confluent.examples.clients.basicavro.OrderStatus.Builder newBuilder() {
    return new io.confluent.examples.clients.basicavro.OrderStatus.Builder();
  }

  /**
   * Creates a new OrderStatus RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderStatus RecordBuilder
   */
  public static io.confluent.examples.clients.basicavro.OrderStatus.Builder newBuilder(io.confluent.examples.clients.basicavro.OrderStatus.Builder other) {
    if (other == null) {
      return new io.confluent.examples.clients.basicavro.OrderStatus.Builder();
    } else {
      return new io.confluent.examples.clients.basicavro.OrderStatus.Builder(other);
    }
  }

  /**
   * Creates a new OrderStatus RecordBuilder by copying an existing OrderStatus instance.
   * @param other The existing instance to copy.
   * @return A new OrderStatus RecordBuilder
   */
  public static io.confluent.examples.clients.basicavro.OrderStatus.Builder newBuilder(io.confluent.examples.clients.basicavro.OrderStatus other) {
    if (other == null) {
      return new io.confluent.examples.clients.basicavro.OrderStatus.Builder();
    } else {
      return new io.confluent.examples.clients.basicavro.OrderStatus.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderStatus instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderStatus>
    implements org.apache.avro.data.RecordBuilder<OrderStatus> {

    private java.lang.String statusMessage;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.examples.clients.basicavro.OrderStatus.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.statusMessage)) {
        this.statusMessage = data().deepCopy(fields()[0].schema(), other.statusMessage);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderStatus instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.examples.clients.basicavro.OrderStatus other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.statusMessage)) {
        this.statusMessage = data().deepCopy(fields()[0].schema(), other.statusMessage);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'statusMessage' field.
      * @return The value.
      */
    public java.lang.String getStatusMessage() {
      return statusMessage;
    }


    /**
      * Sets the value of the 'statusMessage' field.
      * @param value The value of 'statusMessage'.
      * @return This builder.
      */
    public io.confluent.examples.clients.basicavro.OrderStatus.Builder setStatusMessage(java.lang.String value) {
      validate(fields()[0], value);
      this.statusMessage = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'statusMessage' field has been set.
      * @return True if the 'statusMessage' field has been set, false otherwise.
      */
    public boolean hasStatusMessage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'statusMessage' field.
      * @return This builder.
      */
    public io.confluent.examples.clients.basicavro.OrderStatus.Builder clearStatusMessage() {
      statusMessage = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderStatus build() {
      try {
        OrderStatus record = new OrderStatus();
        record.statusMessage = fieldSetFlags()[0] ? this.statusMessage : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderStatus>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderStatus>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderStatus>
    READER$ = (org.apache.avro.io.DatumReader<OrderStatus>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.statusMessage);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.statusMessage = in.readString();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.statusMessage = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










